(function($){"use strict";function handlePreloader(){if($('.preloader').length){$('.preloader').delay(200).fadeOut(500)}}
    function headerStyle(){if($('.main-header').length){var windowpos=$(window).scrollTop();var siteHeader=$('.main-header');var scrollLink=$('.scroll-to-top');if(windowpos>=1){siteHeader.addClass('fixed-header');scrollLink.fadeIn(300)}else{siteHeader.removeClass('fixed-header');scrollLink.fadeOut(300)}}}
    headerStyle();if($('.main-header li.dropdown ul').length){$('.main-header .navigation li.dropdown').append('<div class="dropdown-btn"><span class="fa fa-angle-down"></span></div>');$('.main-header li.dropdown .dropdown-btn').on('click',function(){$(this).prev('ul').slideToggle(500)})}
    if($('.main-slider .tp-banner').length){var MainSlider=$('.main-slider');var strtHeight=MainSlider.attr('data-start-height');var slideOverlay="'"+MainSlider.attr('data-slide-overlay')+"'";$('.main-slider .tp-banner').show().revolution({dottedOverlay:slideOverlay,delay:10000,startwidth:1200,startheight:strtHeight,hideThumbs:600,thumbWidth:80,thumbHeight:50,thumbAmount:5,navigationType:"bullet",navigationArrows:"0",navigationStyle:"preview3",touchenabled:"on",onHoverStop:"off",swipe_velocity:0.7,swipe_min_touches:1,swipe_max_touches:1,drag_block_vertical:!1,parallax:"mouse",parallaxBgFreeze:"on",parallaxLevels:[7,4,3,2,5,4,3,2,1,0],keyboardNavigation:"off",navigationHAlign:"center",navigationVAlign:"bottom",navigationHOffset:0,navigationVOffset:50,soloArrowLeftHalign:"left",soloArrowLeftValign:"bottom",soloArrowLeftHOffset:20,soloArrowLeftVOffset:0,soloArrowRightHalign:"right",soloArrowRightValign:"center",soloArrowRightHOffset:20,soloArrowRightVOffset:0,shadow:0,fullWidth:"on",fullScreen:"off",spinner:"spinner4",stopLoop:"off",stopAfterLoops:-1,stopAtSlide:-1,shuffle:"off",autoHeight:"off",forceFullWidth:"on",hideThumbsOnMobile:"on",hideNavDelayOnMobile:1500,hideBulletsOnMobile:"on",hideArrowsOnMobile:"on",hideThumbsUnderResolution:0,hideSliderAtLimit:0,hideCaptionAtLimit:0,hideAllCaptionAtLilmit:0,startWithSlide:0,videoJsPath:"",fullScreenOffsetContainer:""})}
    if($('.scroll-nav').length){$('.scroll-nav ul').onePageNav()}
    if($('.single-item-carousel').length){$('.single-item-carousel').owlCarousel({loop:!0,margin:50,items:1,nav:!0,smartSpeed:700,autoplay:5000,navText:['<span class="flaticon-arrows-3"></span>','<span class="flaticon-right-arrow"></span>'],})}
    if($('.team-carousel').length){$('.team-carousel').owlCarousel({loop:!0,margin:30,nav:!0,smartSpeed:500,autoplay:!0,navText:['<span class="fa fa-angle-left"></span>','<span class="fa fa-angle-right"></span>'],responsive:{0:{items:1},600:{items:2},700:{items:2},800:{items:3},1024:{items:3},1200:{items:4}}})}
    if($('.sponsors-slider').length){$('.sponsors-slider').owlCarousel({loop:!0,margin:30,nav:!0,smartSpeed:500,autoplay:4000,navText:['<span class="fa fa-angle-left"></span>','<span class="fa fa-angle-right"></span>'],responsive:{0:{items:1},600:{items:2},800:{items:3},1024:{items:4},1200:{items:4}}})}
    if($('.screenshots-carousel-one').length){$('.screenshots-carousel-one').owlCarousel({loop:!0,margin:30,nav:!0,smartSpeed:500,autoplay:!0,navText:['<span class="fa fa-angle-left"></span>','<span class="fa fa-angle-right"></span>'],responsive:{0:{items:1},600:{items:2},800:{items:3},1024:{items:4},1200:{items:3},1400:{items:3},1920:{items:4}}})}
    if($('.three-items-carousel').length){$('.three-items-carousel').owlCarousel({loop:!0,margin:30,nav:!0,smartSpeed:500,autoplay:!0,navText:['<span class="fa fa-angle-left"></span>','<span class="fa fa-angle-right"></span>'],responsive:{0:{items:1},600:{items:1},800:{items:2},1024:{items:2},1200:{items:3}}})}
    if($('.four-item-carousel').length){$('.four-item-carousel').owlCarousel({loop:!0,margin:30,nav:!0,smartSpeed:500,autoplay:!0,navText:['<span class="fa fa-angle-left"></span>','<span class="fa fa-angle-right"></span>'],responsive:{0:{items:1},600:{items:2},700:{items:2},800:{items:3},1024:{items:4},1200:{items:4}}})}
    if($('.lightbox-image').length){$('.lightbox-image').fancybox({openEffect:'fade',closeEffect:'fade',helpers:{media:{}}})}
    if($('.accordion-box').length){$(".accordion-box").on('click','.acc-btn',function(){var outerBox=$(this).parents('.accordion-box');var target=$(this).parents('.accordion');if($(this).hasClass('active')!==!0){$('.accordion .acc-btn').removeClass('active')}
        if($(this).next('.acc-content').is(':visible')){return!1}else{$(this).addClass('active');$(outerBox).children('.accordion').removeClass('active-block');$(outerBox).find('.accordion').children('.acc-content').slideUp(300);target.addClass('active-block');$(this).next('.acc-content').slideDown(300)}})}
    if($('#contact-form').length){$('#contact-form').validate({rules:{username:{required:!0},email:{required:!0,email:!0},message:{required:!0}}})}
    if($('.scroll-to-target').length){$(".scroll-to-target").on('click',function(){var target=$(this).attr('data-target');$('html, body').animate({scrollTop:$(target).offset().top},1000)})}
    if($('.wow').length){var wow=new WOW({boxClass:'wow',animateClass:'animated',offset:0,mobile:!0,live:!0});wow.init()}
    $(window).on('scroll',function(){headerStyle()});$(window).on('load',function(){handlePreloader()})})(window.jQuery)